<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <StripSymbols>true</StripSymbols>
    <OptimizationPreference>Speed</OptimizationPreference>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FParsec" Version="1.1.1" />
    <PackageReference Include="ReadLine" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="Ast.fs" />
    <Compile Include="Check.fs" />
    <Compile Include="Parser.fs" />
    <Compile Include="Complete.fs" />
    <Compile Include="Session.fs" />
    <Compile Include="Extern.fs" />
    <Compile Include="Diagnose.fs" />
    <Compile Include="Proc.fs" />
    <Compile Include="Eval.fs" />
    <Compile Include="Builtins.fs" />
    <Compile Include="Prelude.fs" />
    <Compile Include="Script.fs" />
    <Compile Include="Fmt.fs" />
    <Compile Include="Repl.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
