#!/usr/bin/env python3
# The grammar manifest [D:ts-split] — the GENERATED contract between the
# language and every grammar, in-repo or split out. One extraction (the
# same regexes the inventory gates always used), one JSON artifact:
#
#   editors/grammar-manifest.json
#
# `--check` verifies the committed file is CURRENT (the main repo's
# currency gate); without it, the file is (re)written. The tree-sitter
# repo's CI checks ITSELF against this file at its pinned weir ref —
# the main repo no longer reads tree-sitter sources at all.
#
# Deliberately NO volatile field (sha/date): the manifest must be byte-
# stable across commits that do not move the sets, or every commit
# dirties it. Git versions the content; the grammar repo's tracked ref
# names the language version it follows.
import json, re, sys, os

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

parser_src = open(f"{root}/src/Weir/Parser.fs").read()
# the list closes with `"word" ]` on its last entry; comments inside
# carry [D:...] brackets, so capture to that closing shape, not to `]`
kw_block = re.search(r"let (?:private )?keywords[^=]*=(.*?\"\w+\" \])", parser_src, re.S)
keywords = sorted(set(re.findall(r'"(\w+)"', kw_block.group(1))))

ast_src = open(f"{root}/src/Weir/Ast.fs").read()
wk_block = re.search(r"let withinKinds[^=]*=\n(.*?)\n\n", ast_src, re.S).group(1)
within_kinds = sorted(set(re.findall(r'Name = "(\w+)"', wk_block)))

builtins_src = open(f"{root}/src/Weir/Builtins.fs").read()
adapters = {
    "from": sorted(set(re.findall(r'"from (\w+)",', builtins_src))),
    "to": sorted(set(re.findall(r'"to (\w+)",', builtins_src))),
}

# line-end district markers [D:text-block]: the parser's blockHeads list
# is the source; $-interpolated spellings ($<<<) derive in the grammars.
# heads may be GLYPHS (<<<), so the capture is any quoted string
bh_block = re.search(r'let blockHeads = \[([^\]]*)\]', parser_src).group(1)
block_heads = sorted(set(re.findall(r'"([^"]+)"', bh_block)))

manifest = {
    "_": "generated by ci/grammar-manifest.py — do not edit; the currency gate diffs this",
    "keywords": keywords,
    "withinKinds": within_kinds,
    "adapters": adapters,
    "blockHeads": block_heads,
}

target = f"{root}/editors/grammar-manifest.json"
rendered = json.dumps(manifest, indent=2, sort_keys=True) + "\n"

if "--check" in sys.argv:
    current = open(target).read() if os.path.exists(target) else ""
    if current != rendered:
        print("grammar-manifest.json is STALE — regenerate: python3 ci/grammar-manifest.py")
        sys.exit(1)
    print(f"grammar manifest current ({len(keywords)} keywords, "
          f"{len(within_kinds)} within kinds, "
          f"{len(adapters['from'])}+{len(adapters['to'])} adapters, "
          f"{len(block_heads)} block heads)")
else:
    open(target, "w").write(rendered)
    print(f"wrote {target}")
