/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 18
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 92
#define ALIAS_COUNT 0
#define TOKEN_COUNT 81
#define EXTERNAL_TOKEN_COUNT 7
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  sym_hash_line = 3,
  sym_attribute = 4,
  anon_sym_let = 5,
  anon_sym__ = 6,
  anon_sym_type = 7,
  anon_sym_in = 8,
  anon_sym_fun = 9,
  anon_sym_match = 10,
  anon_sym_with = 11,
  anon_sym_of = 12,
  anon_sym_if = 13,
  anon_sym_then = 14,
  anon_sym_elif = 15,
  anon_sym_else = 16,
  anon_sym_when = 17,
  anon_sym_from = 18,
  anon_sym_to = 19,
  anon_sym_for = 20,
  anon_sym_do = 21,
  anon_sym_module = 22,
  anon_sym_import = 23,
  anon_sym_within = 24,
  anon_sym_true = 25,
  anon_sym_false = 26,
  sym_string = 27,
  sym_raw_verbatim = 28,
  sym_raw_string = 29,
  anon_sym_DOLLAR_DQUOTE = 30,
  anon_sym_DQUOTE = 31,
  sym_interp_text = 32,
  sym_interp_escape = 33,
  sym_interp_hole = 34,
  sym_splat = 35,
  sym_sigil = 36,
  sym_splice = 37,
  sym_bang_sigil = 38,
  sym_adapter = 39,
  sym_number = 40,
  sym_constructor = 41,
  anon_sym_PIPE_GT = 42,
  anon_sym_GT_GT = 43,
  anon_sym_DASH_GT = 44,
  anon_sym_COLON_COLON = 45,
  anon_sym_EQ_EQ = 46,
  anon_sym_BANG_EQ = 47,
  anon_sym_LT_EQ = 48,
  anon_sym_GT_EQ = 49,
  anon_sym_AMP_AMP = 50,
  anon_sym_PIPE_PIPE = 51,
  anon_sym_DOT_DOT = 52,
  anon_sym_PIPE = 53,
  anon_sym_EQ = 54,
  anon_sym_LT = 55,
  anon_sym_GT = 56,
  anon_sym_PLUS = 57,
  anon_sym_DASH = 58,
  anon_sym_STAR = 59,
  anon_sym_SLASH = 60,
  anon_sym_PERCENT = 61,
  anon_sym_CARET = 62,
  anon_sym_DOT = 63,
  anon_sym_LPAREN = 64,
  anon_sym_RPAREN = 65,
  anon_sym_LBRACK = 66,
  anon_sym_RBRACK = 67,
  anon_sym_LBRACE = 68,
  anon_sym_RBRACE = 69,
  anon_sym_SEMI = 70,
  anon_sym_COMMA = 71,
  anon_sym_COLON = 72,
  sym_stray = 73,
  sym_type_param = 74,
  sym_yaml_marker = 75,
  sym_yaml_key = 76,
  sym_yaml_text = 77,
  sym_yaml_for = 78,
  sym_yaml_hole = 79,
  sym__yaml_end = 80,
  sym_source_file = 81,
  sym__item = 82,
  sym_let_head = 83,
  sym_type_head = 84,
  sym_keyword = 85,
  sym_boolean = 86,
  sym_interp_string = 87,
  sym_operator = 88,
  sym_punctuation = 89,
  aux_sym_source_file_repeat1 = 90,
  aux_sym_interp_string_repeat1 = 91,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_hash_line] = "hash_line",
  [sym_attribute] = "attribute",
  [anon_sym_let] = "let",
  [anon_sym__] = "_",
  [anon_sym_type] = "type",
  [anon_sym_in] = "in",
  [anon_sym_fun] = "fun",
  [anon_sym_match] = "match",
  [anon_sym_with] = "with",
  [anon_sym_of] = "of",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_elif] = "elif",
  [anon_sym_else] = "else",
  [anon_sym_when] = "when",
  [anon_sym_from] = "from",
  [anon_sym_to] = "to",
  [anon_sym_for] = "for",
  [anon_sym_do] = "do",
  [anon_sym_module] = "module",
  [anon_sym_import] = "import",
  [anon_sym_within] = "within",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_string] = "string",
  [sym_raw_verbatim] = "raw_verbatim",
  [sym_raw_string] = "raw_string",
  [anon_sym_DOLLAR_DQUOTE] = "$\"",
  [anon_sym_DQUOTE] = "\"",
  [sym_interp_text] = "interp_text",
  [sym_interp_escape] = "interp_escape",
  [sym_interp_hole] = "interp_hole",
  [sym_splat] = "splat",
  [sym_sigil] = "sigil",
  [sym_splice] = "splice",
  [sym_bang_sigil] = "bang_sigil",
  [sym_adapter] = "adapter",
  [sym_number] = "number",
  [sym_constructor] = "constructor",
  [anon_sym_PIPE_GT] = "|>",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_AMP_AMP] = "&&",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_PIPE] = "|",
  [anon_sym_EQ] = "=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_CARET] = "^",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [sym_stray] = "stray",
  [sym_type_param] = "type_param",
  [sym_yaml_marker] = "yaml_marker",
  [sym_yaml_key] = "yaml_key",
  [sym_yaml_text] = "yaml_text",
  [sym_yaml_for] = "yaml_for",
  [sym_yaml_hole] = "yaml_hole",
  [sym__yaml_end] = "_yaml_end",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_let_head] = "let_head",
  [sym_type_head] = "type_head",
  [sym_keyword] = "keyword",
  [sym_boolean] = "boolean",
  [sym_interp_string] = "interp_string",
  [sym_operator] = "operator",
  [sym_punctuation] = "punctuation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_interp_string_repeat1] = "interp_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_hash_line] = sym_hash_line,
  [sym_attribute] = sym_attribute,
  [anon_sym_let] = anon_sym_let,
  [anon_sym__] = anon_sym__,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_fun] = anon_sym_fun,
  [anon_sym_match] = anon_sym_match,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_of] = anon_sym_of,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_when] = anon_sym_when,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_to] = anon_sym_to,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_do] = anon_sym_do,
  [anon_sym_module] = anon_sym_module,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_within] = anon_sym_within,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_string] = sym_string,
  [sym_raw_verbatim] = sym_raw_verbatim,
  [sym_raw_string] = sym_raw_string,
  [anon_sym_DOLLAR_DQUOTE] = anon_sym_DOLLAR_DQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_interp_text] = sym_interp_text,
  [sym_interp_escape] = sym_interp_escape,
  [sym_interp_hole] = sym_interp_hole,
  [sym_splat] = sym_splat,
  [sym_sigil] = sym_sigil,
  [sym_splice] = sym_splice,
  [sym_bang_sigil] = sym_bang_sigil,
  [sym_adapter] = sym_adapter,
  [sym_number] = sym_number,
  [sym_constructor] = sym_constructor,
  [anon_sym_PIPE_GT] = anon_sym_PIPE_GT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_AMP_AMP] = anon_sym_AMP_AMP,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_stray] = sym_stray,
  [sym_type_param] = sym_type_param,
  [sym_yaml_marker] = sym_yaml_marker,
  [sym_yaml_key] = sym_yaml_key,
  [sym_yaml_text] = sym_yaml_text,
  [sym_yaml_for] = sym_yaml_for,
  [sym_yaml_hole] = sym_yaml_hole,
  [sym__yaml_end] = sym__yaml_end,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_let_head] = sym_let_head,
  [sym_type_head] = sym_type_head,
  [sym_keyword] = sym_keyword,
  [sym_boolean] = sym_boolean,
  [sym_interp_string] = sym_interp_string,
  [sym_operator] = sym_operator,
  [sym_punctuation] = sym_punctuation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_interp_string_repeat1] = aux_sym_interp_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_hash_line] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym__] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fun] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_match] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_of] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_when] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_to] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_do] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_module] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_within] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_verbatim] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAR_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_interp_text] = {
    .visible = true,
    .named = true,
  },
  [sym_interp_escape] = {
    .visible = true,
    .named = true,
  },
  [sym_interp_hole] = {
    .visible = true,
    .named = true,
  },
  [sym_splat] = {
    .visible = true,
    .named = true,
  },
  [sym_sigil] = {
    .visible = true,
    .named = true,
  },
  [sym_splice] = {
    .visible = true,
    .named = true,
  },
  [sym_bang_sigil] = {
    .visible = true,
    .named = true,
  },
  [sym_adapter] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_constructor] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PIPE_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_stray] = {
    .visible = true,
    .named = true,
  },
  [sym_type_param] = {
    .visible = true,
    .named = true,
  },
  [sym_yaml_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_yaml_key] = {
    .visible = true,
    .named = true,
  },
  [sym_yaml_text] = {
    .visible = true,
    .named = true,
  },
  [sym_yaml_for] = {
    .visible = true,
    .named = true,
  },
  [sym_yaml_hole] = {
    .visible = true,
    .named = true,
  },
  [sym__yaml_end] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_let_head] = {
    .visible = true,
    .named = true,
  },
  [sym_type_head] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_interp_string] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_interp_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '!', 86,
        '"', 27,
        '#', 21,
        '$', 81,
        '%', 68,
        '&', 84,
        '\'', 85,
        '(', 71,
        ')', 72,
        '*', 66,
        '+', 64,
        ',', 78,
        '-', 65,
        '.', 70,
        '/', 67,
        ':', 79,
        ';', 77,
        '<', 62,
        '=', 61,
        '>', 63,
        '@', 82,
        '[', 73,
        ']', 74,
        '^', 69,
        'f', 46,
        't', 44,
        '{', 75,
        '|', 60,
        '}', 76,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(42);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 27,
        '/', 30,
        '\\', 16,
        '{', 5,
        '}', 14,
        '\t', 29,
        '\n', 29,
        '\r', 29,
        ' ', 29,
      );
      if (lookahead != 0) ADVANCE(31);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(24);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(6);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '{') ADVANCE(33);
      if (lookahead == '}') ADVANCE(34);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '}') ADVANCE(34);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '\'') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '(') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '(') ADVANCE(35);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(40);
      END_STATE();
    case 12:
      if (lookahead == 'm') ADVANCE(11);
      END_STATE();
    case 13:
      if (lookahead == 'y') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(32);
      END_STATE();
    case 15:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(3);
      END_STATE();
    case 16:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 17:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '!', 86,
        '"', 83,
        '#', 21,
        '$', 81,
        '%', 68,
        '&', 84,
        '\'', 85,
        '(', 71,
        ')', 72,
        '*', 66,
        '+', 64,
        ',', 78,
        '-', 65,
        '.', 70,
        '/', 67,
        ':', 79,
        ';', 77,
        '<', 62,
        '=', 61,
        '>', 63,
        '@', 82,
        '[', 73,
        ']', 74,
        '^', 69,
        'f', 46,
        't', 44,
        '{', 75,
        '|', 60,
        '}', 76,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(42);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      ADVANCE_MAP(
        '!', 86,
        '#', 21,
        '$', 81,
        '%', 68,
        '&', 84,
        '\'', 85,
        '(', 71,
        ')', 72,
        '*', 66,
        '+', 64,
        ',', 78,
        '-', 65,
        '.', 70,
        '/', 67,
        ':', 79,
        ';', 77,
        '<', 62,
        '=', 61,
        '>', 63,
        '@', 82,
        '[', 73,
        ']', 74,
        '^', 69,
        'f', 46,
        't', 44,
        '{', 75,
        '|', 60,
        '}', 76,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(42);
      if (lookahead != 0) ADVANCE(80);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_hash_line);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_attribute);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_raw_verbatim);
      if (lookahead == '"') ADVANCE(2);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_raw_string);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DOLLAR_DQUOTE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_interp_text);
      if (lookahead == '\n') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_interp_text);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_interp_text);
      if (lookahead == '/') ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_interp_text);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_interp_escape);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_interp_escape);
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '}') ADVANCE(34);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_interp_hole);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_splat);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_splat);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_sigil);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_splice);
      if (lookahead == '(') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_bang_sigil);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_adapter);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_constructor);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'm') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(47);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(43);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_PIPE_GT);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_AMP_AMP);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '>') ADVANCE(49);
      if (lookahead == '|') ADVANCE(58);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(53);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(55);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(56);
      if (lookahead == '>') ADVANCE(50);
      if (lookahead == ']') ADVANCE(22);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(51);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '/') ADVANCE(20);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (lookahead == '.') ADVANCE(59);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '<') ADVANCE(22);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(52);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_stray);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_stray);
      if (lookahead == '"') ADVANCE(26);
      if (lookahead == '(') ADVANCE(37);
      if (lookahead == '@') ADVANCE(9);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_stray);
      if (lookahead == '"') ADVANCE(2);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_stray);
      if (lookahead == '"') ADVANCE(23);
      if (lookahead == '\\') ADVANCE(15);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_stray);
      if (lookahead == '&') ADVANCE(57);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_stray);
      if (lookahead == '\'') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(7);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_stray);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == '=') ADVANCE(54);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(8);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        '_', 1,
        'd', 2,
        'e', 3,
        'f', 4,
        'i', 5,
        'l', 6,
        'm', 7,
        'o', 8,
        't', 9,
        'w', 10,
      );
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(anon_sym__);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(13);
      if (lookahead == 'o') ADVANCE(14);
      if (lookahead == 'r') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 5:
      if (lookahead == 'f') ADVANCE(17);
      if (lookahead == 'm') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(21);
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(23);
      END_STATE();
    case 9:
      if (lookahead == 'h') ADVANCE(24);
      if (lookahead == 'o') ADVANCE(25);
      if (lookahead == 'r') ADVANCE(26);
      if (lookahead == 'y') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'h') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_do);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(30);
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(32);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(35);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(36);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 21:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 22:
      if (lookahead == 'd') ADVANCE(39);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_of);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_to);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(41);
      END_STATE();
    case 27:
      if (lookahead == 'p') ADVANCE(42);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(44);
      END_STATE();
    case 30:
      if (lookahead == 'f') ADVANCE(45);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(46);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(47);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 34:
      if (lookahead == 'm') ADVANCE(48);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_fun);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(49);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 38:
      if (lookahead == 'c') ADVANCE(50);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(51);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(52);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 44:
      if (lookahead == 'h') ADVANCE(56);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_elif);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 49:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 50:
      if (lookahead == 'h') ADVANCE(59);
      END_STATE();
    case 51:
      if (lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_when);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_with);
      if (lookahead == 'i') ADVANCE(61);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 58:
      if (lookahead == 't') ADVANCE(62);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_match);
      END_STATE();
    case 60:
      if (lookahead == 'e') ADVANCE(63);
      END_STATE();
    case 61:
      if (lookahead == 'n') ADVANCE(64);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_module);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_within);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 17, .external_lex_state = 1},
  [2] = {.lex_state = 17, .external_lex_state = 1},
  [3] = {.lex_state = 17, .external_lex_state = 1},
  [4] = {.lex_state = 17, .external_lex_state = 1},
  [5] = {.lex_state = 17, .external_lex_state = 1},
  [6] = {.lex_state = 17, .external_lex_state = 1},
  [7] = {.lex_state = 17, .external_lex_state = 1},
  [8] = {.lex_state = 17, .external_lex_state = 1},
  [9] = {.lex_state = 17, .external_lex_state = 1},
  [10] = {.lex_state = 17, .external_lex_state = 1},
  [11] = {.lex_state = 17, .external_lex_state = 1},
  [12] = {.lex_state = 17, .external_lex_state = 1},
  [13] = {.lex_state = 17, .external_lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_hash_line] = ACTIONS(1),
    [sym_attribute] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym__] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_fun] = ACTIONS(1),
    [anon_sym_match] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_of] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_when] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_to] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_do] = ACTIONS(1),
    [anon_sym_module] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_within] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_raw_verbatim] = ACTIONS(1),
    [sym_raw_string] = ACTIONS(1),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_splat] = ACTIONS(1),
    [sym_sigil] = ACTIONS(1),
    [sym_splice] = ACTIONS(1),
    [sym_bang_sigil] = ACTIONS(1),
    [sym_adapter] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_constructor] = ACTIONS(1),
    [anon_sym_PIPE_GT] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_AMP_AMP] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_stray] = ACTIONS(1),
    [sym_type_param] = ACTIONS(1),
    [sym_yaml_marker] = ACTIONS(1),
    [sym_yaml_key] = ACTIONS(1),
    [sym_yaml_text] = ACTIONS(1),
    [sym_yaml_for] = ACTIONS(1),
    [sym_yaml_hole] = ACTIONS(1),
    [sym__yaml_end] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(17),
    [sym__item] = STATE(2),
    [sym_let_head] = STATE(2),
    [sym_type_head] = STATE(2),
    [sym_keyword] = STATE(2),
    [sym_boolean] = STATE(2),
    [sym_interp_string] = STATE(2),
    [sym_operator] = STATE(2),
    [sym_punctuation] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [sym_hash_line] = ACTIONS(9),
    [sym_attribute] = ACTIONS(9),
    [anon_sym_let] = ACTIONS(11),
    [anon_sym__] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(15),
    [anon_sym_in] = ACTIONS(17),
    [anon_sym_fun] = ACTIONS(17),
    [anon_sym_match] = ACTIONS(17),
    [anon_sym_with] = ACTIONS(17),
    [anon_sym_of] = ACTIONS(17),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_then] = ACTIONS(17),
    [anon_sym_elif] = ACTIONS(17),
    [anon_sym_else] = ACTIONS(17),
    [anon_sym_when] = ACTIONS(17),
    [anon_sym_from] = ACTIONS(17),
    [anon_sym_to] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(17),
    [anon_sym_do] = ACTIONS(17),
    [anon_sym_module] = ACTIONS(17),
    [anon_sym_import] = ACTIONS(17),
    [anon_sym_within] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_string] = ACTIONS(9),
    [sym_raw_verbatim] = ACTIONS(9),
    [sym_raw_string] = ACTIONS(9),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(21),
    [sym_splat] = ACTIONS(9),
    [sym_sigil] = ACTIONS(9),
    [sym_splice] = ACTIONS(7),
    [sym_bang_sigil] = ACTIONS(9),
    [sym_adapter] = ACTIONS(9),
    [sym_number] = ACTIONS(9),
    [sym_constructor] = ACTIONS(9),
    [anon_sym_PIPE_GT] = ACTIONS(23),
    [anon_sym_GT_GT] = ACTIONS(23),
    [anon_sym_DASH_GT] = ACTIONS(23),
    [anon_sym_COLON_COLON] = ACTIONS(23),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_AMP_AMP] = ACTIONS(23),
    [anon_sym_PIPE_PIPE] = ACTIONS(23),
    [anon_sym_DOT_DOT] = ACTIONS(23),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_CARET] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_SEMI] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(25),
    [anon_sym_COLON] = ACTIONS(27),
    [sym_stray] = ACTIONS(7),
    [sym_type_param] = ACTIONS(9),
    [sym_yaml_marker] = ACTIONS(9),
    [sym_yaml_key] = ACTIONS(9),
    [sym_yaml_text] = ACTIONS(9),
    [sym_yaml_for] = ACTIONS(9),
    [sym_yaml_hole] = ACTIONS(9),
    [sym__yaml_end] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__item] = STATE(3),
    [sym_let_head] = STATE(3),
    [sym_type_head] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_interp_string] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_punctuation] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_identifier] = ACTIONS(31),
    [sym_comment] = ACTIONS(3),
    [sym_hash_line] = ACTIONS(33),
    [sym_attribute] = ACTIONS(33),
    [anon_sym_let] = ACTIONS(11),
    [anon_sym__] = ACTIONS(13),
    [anon_sym_type] = ACTIONS(15),
    [anon_sym_in] = ACTIONS(17),
    [anon_sym_fun] = ACTIONS(17),
    [anon_sym_match] = ACTIONS(17),
    [anon_sym_with] = ACTIONS(17),
    [anon_sym_of] = ACTIONS(17),
    [anon_sym_if] = ACTIONS(17),
    [anon_sym_then] = ACTIONS(17),
    [anon_sym_elif] = ACTIONS(17),
    [anon_sym_else] = ACTIONS(17),
    [anon_sym_when] = ACTIONS(17),
    [anon_sym_from] = ACTIONS(17),
    [anon_sym_to] = ACTIONS(17),
    [anon_sym_for] = ACTIONS(17),
    [anon_sym_do] = ACTIONS(17),
    [anon_sym_module] = ACTIONS(17),
    [anon_sym_import] = ACTIONS(17),
    [anon_sym_within] = ACTIONS(17),
    [anon_sym_true] = ACTIONS(19),
    [anon_sym_false] = ACTIONS(19),
    [sym_string] = ACTIONS(33),
    [sym_raw_verbatim] = ACTIONS(33),
    [sym_raw_string] = ACTIONS(33),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(21),
    [sym_splat] = ACTIONS(33),
    [sym_sigil] = ACTIONS(33),
    [sym_splice] = ACTIONS(31),
    [sym_bang_sigil] = ACTIONS(33),
    [sym_adapter] = ACTIONS(33),
    [sym_number] = ACTIONS(33),
    [sym_constructor] = ACTIONS(33),
    [anon_sym_PIPE_GT] = ACTIONS(23),
    [anon_sym_GT_GT] = ACTIONS(23),
    [anon_sym_DASH_GT] = ACTIONS(23),
    [anon_sym_COLON_COLON] = ACTIONS(23),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_BANG_EQ] = ACTIONS(23),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(23),
    [anon_sym_AMP_AMP] = ACTIONS(23),
    [anon_sym_PIPE_PIPE] = ACTIONS(23),
    [anon_sym_DOT_DOT] = ACTIONS(23),
    [anon_sym_PIPE] = ACTIONS(13),
    [anon_sym_EQ] = ACTIONS(13),
    [anon_sym_LT] = ACTIONS(13),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(13),
    [anon_sym_STAR] = ACTIONS(23),
    [anon_sym_SLASH] = ACTIONS(13),
    [anon_sym_PERCENT] = ACTIONS(23),
    [anon_sym_CARET] = ACTIONS(23),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_SEMI] = ACTIONS(25),
    [anon_sym_COMMA] = ACTIONS(25),
    [anon_sym_COLON] = ACTIONS(27),
    [sym_stray] = ACTIONS(31),
    [sym_type_param] = ACTIONS(33),
    [sym_yaml_marker] = ACTIONS(33),
    [sym_yaml_key] = ACTIONS(33),
    [sym_yaml_text] = ACTIONS(33),
    [sym_yaml_for] = ACTIONS(33),
    [sym_yaml_hole] = ACTIONS(33),
    [sym__yaml_end] = ACTIONS(33),
  },
  [STATE(3)] = {
    [sym__item] = STATE(3),
    [sym_let_head] = STATE(3),
    [sym_type_head] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_boolean] = STATE(3),
    [sym_interp_string] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_punctuation] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(35),
    [sym_identifier] = ACTIONS(37),
    [sym_comment] = ACTIONS(3),
    [sym_hash_line] = ACTIONS(40),
    [sym_attribute] = ACTIONS(40),
    [anon_sym_let] = ACTIONS(43),
    [anon_sym__] = ACTIONS(46),
    [anon_sym_type] = ACTIONS(49),
    [anon_sym_in] = ACTIONS(52),
    [anon_sym_fun] = ACTIONS(52),
    [anon_sym_match] = ACTIONS(52),
    [anon_sym_with] = ACTIONS(52),
    [anon_sym_of] = ACTIONS(52),
    [anon_sym_if] = ACTIONS(52),
    [anon_sym_then] = ACTIONS(52),
    [anon_sym_elif] = ACTIONS(52),
    [anon_sym_else] = ACTIONS(52),
    [anon_sym_when] = ACTIONS(52),
    [anon_sym_from] = ACTIONS(52),
    [anon_sym_to] = ACTIONS(52),
    [anon_sym_for] = ACTIONS(52),
    [anon_sym_do] = ACTIONS(52),
    [anon_sym_module] = ACTIONS(52),
    [anon_sym_import] = ACTIONS(52),
    [anon_sym_within] = ACTIONS(52),
    [anon_sym_true] = ACTIONS(55),
    [anon_sym_false] = ACTIONS(55),
    [sym_string] = ACTIONS(40),
    [sym_raw_verbatim] = ACTIONS(40),
    [sym_raw_string] = ACTIONS(40),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(58),
    [sym_splat] = ACTIONS(40),
    [sym_sigil] = ACTIONS(40),
    [sym_splice] = ACTIONS(37),
    [sym_bang_sigil] = ACTIONS(40),
    [sym_adapter] = ACTIONS(40),
    [sym_number] = ACTIONS(40),
    [sym_constructor] = ACTIONS(40),
    [anon_sym_PIPE_GT] = ACTIONS(61),
    [anon_sym_GT_GT] = ACTIONS(61),
    [anon_sym_DASH_GT] = ACTIONS(61),
    [anon_sym_COLON_COLON] = ACTIONS(61),
    [anon_sym_EQ_EQ] = ACTIONS(61),
    [anon_sym_BANG_EQ] = ACTIONS(61),
    [anon_sym_LT_EQ] = ACTIONS(61),
    [anon_sym_GT_EQ] = ACTIONS(61),
    [anon_sym_AMP_AMP] = ACTIONS(61),
    [anon_sym_PIPE_PIPE] = ACTIONS(61),
    [anon_sym_DOT_DOT] = ACTIONS(61),
    [anon_sym_PIPE] = ACTIONS(46),
    [anon_sym_EQ] = ACTIONS(46),
    [anon_sym_LT] = ACTIONS(46),
    [anon_sym_GT] = ACTIONS(46),
    [anon_sym_PLUS] = ACTIONS(61),
    [anon_sym_DASH] = ACTIONS(46),
    [anon_sym_STAR] = ACTIONS(61),
    [anon_sym_SLASH] = ACTIONS(46),
    [anon_sym_PERCENT] = ACTIONS(61),
    [anon_sym_CARET] = ACTIONS(61),
    [anon_sym_DOT] = ACTIONS(46),
    [anon_sym_LPAREN] = ACTIONS(64),
    [anon_sym_RPAREN] = ACTIONS(64),
    [anon_sym_LBRACK] = ACTIONS(67),
    [anon_sym_RBRACK] = ACTIONS(64),
    [anon_sym_LBRACE] = ACTIONS(64),
    [anon_sym_RBRACE] = ACTIONS(64),
    [anon_sym_SEMI] = ACTIONS(64),
    [anon_sym_COMMA] = ACTIONS(64),
    [anon_sym_COLON] = ACTIONS(67),
    [sym_stray] = ACTIONS(37),
    [sym_type_param] = ACTIONS(40),
    [sym_yaml_marker] = ACTIONS(40),
    [sym_yaml_key] = ACTIONS(40),
    [sym_yaml_text] = ACTIONS(40),
    [sym_yaml_for] = ACTIONS(40),
    [sym_yaml_hole] = ACTIONS(40),
    [sym__yaml_end] = ACTIONS(40),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(70),
    [sym_identifier] = ACTIONS(72),
    [sym_comment] = ACTIONS(3),
    [sym_hash_line] = ACTIONS(70),
    [sym_attribute] = ACTIONS(70),
    [anon_sym_let] = ACTIONS(74),
    [anon_sym__] = ACTIONS(72),
    [anon_sym_type] = ACTIONS(74),
    [anon_sym_in] = ACTIONS(74),
    [anon_sym_fun] = ACTIONS(74),
    [anon_sym_match] = ACTIONS(74),
    [anon_sym_with] = ACTIONS(74),
    [anon_sym_of] = ACTIONS(74),
    [anon_sym_if] = ACTIONS(74),
    [anon_sym_then] = ACTIONS(74),
    [anon_sym_elif] = ACTIONS(74),
    [anon_sym_else] = ACTIONS(74),
    [anon_sym_when] = ACTIONS(74),
    [anon_sym_from] = ACTIONS(74),
    [anon_sym_to] = ACTIONS(74),
    [anon_sym_for] = ACTIONS(74),
    [anon_sym_do] = ACTIONS(74),
    [anon_sym_module] = ACTIONS(74),
    [anon_sym_import] = ACTIONS(74),
    [anon_sym_within] = ACTIONS(74),
    [anon_sym_true] = ACTIONS(74),
    [anon_sym_false] = ACTIONS(74),
    [sym_string] = ACTIONS(70),
    [sym_raw_verbatim] = ACTIONS(70),
    [sym_raw_string] = ACTIONS(70),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(70),
    [sym_splat] = ACTIONS(70),
    [sym_sigil] = ACTIONS(70),
    [sym_splice] = ACTIONS(74),
    [sym_bang_sigil] = ACTIONS(70),
    [sym_adapter] = ACTIONS(70),
    [sym_number] = ACTIONS(70),
    [sym_constructor] = ACTIONS(70),
    [anon_sym_PIPE_GT] = ACTIONS(70),
    [anon_sym_GT_GT] = ACTIONS(70),
    [anon_sym_DASH_GT] = ACTIONS(70),
    [anon_sym_COLON_COLON] = ACTIONS(70),
    [anon_sym_EQ_EQ] = ACTIONS(70),
    [anon_sym_BANG_EQ] = ACTIONS(70),
    [anon_sym_LT_EQ] = ACTIONS(70),
    [anon_sym_GT_EQ] = ACTIONS(70),
    [anon_sym_AMP_AMP] = ACTIONS(70),
    [anon_sym_PIPE_PIPE] = ACTIONS(70),
    [anon_sym_DOT_DOT] = ACTIONS(70),
    [anon_sym_PIPE] = ACTIONS(74),
    [anon_sym_EQ] = ACTIONS(74),
    [anon_sym_LT] = ACTIONS(74),
    [anon_sym_GT] = ACTIONS(74),
    [anon_sym_PLUS] = ACTIONS(70),
    [anon_sym_DASH] = ACTIONS(74),
    [anon_sym_STAR] = ACTIONS(70),
    [anon_sym_SLASH] = ACTIONS(74),
    [anon_sym_PERCENT] = ACTIONS(70),
    [anon_sym_CARET] = ACTIONS(70),
    [anon_sym_DOT] = ACTIONS(74),
    [anon_sym_LPAREN] = ACTIONS(70),
    [anon_sym_RPAREN] = ACTIONS(70),
    [anon_sym_LBRACK] = ACTIONS(74),
    [anon_sym_RBRACK] = ACTIONS(70),
    [anon_sym_LBRACE] = ACTIONS(70),
    [anon_sym_RBRACE] = ACTIONS(70),
    [anon_sym_SEMI] = ACTIONS(70),
    [anon_sym_COMMA] = ACTIONS(70),
    [anon_sym_COLON] = ACTIONS(74),
    [sym_stray] = ACTIONS(74),
    [sym_type_param] = ACTIONS(70),
    [sym_yaml_marker] = ACTIONS(70),
    [sym_yaml_key] = ACTIONS(70),
    [sym_yaml_text] = ACTIONS(70),
    [sym_yaml_for] = ACTIONS(70),
    [sym_yaml_hole] = ACTIONS(70),
    [sym__yaml_end] = ACTIONS(70),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(76),
    [sym_identifier] = ACTIONS(78),
    [sym_comment] = ACTIONS(3),
    [sym_hash_line] = ACTIONS(76),
    [sym_attribute] = ACTIONS(76),
    [anon_sym_let] = ACTIONS(78),
    [anon_sym__] = ACTIONS(78),
    [anon_sym_type] = ACTIONS(78),
    [anon_sym_in] = ACTIONS(78),
    [anon_sym_fun] = ACTIONS(78),
    [anon_sym_match] = ACTIONS(78),
    [anon_sym_with] = ACTIONS(78),
    [anon_sym_of] = ACTIONS(78),
    [anon_sym_if] = ACTIONS(78),
    [anon_sym_then] = ACTIONS(78),
    [anon_sym_elif] = ACTIONS(78),
    [anon_sym_else] = ACTIONS(78),
    [anon_sym_when] = ACTIONS(78),
    [anon_sym_from] = ACTIONS(78),
    [anon_sym_to] = ACTIONS(78),
    [anon_sym_for] = ACTIONS(78),
    [anon_sym_do] = ACTIONS(78),
    [anon_sym_module] = ACTIONS(78),
    [anon_sym_import] = ACTIONS(78),
    [anon_sym_within] = ACTIONS(78),
    [anon_sym_true] = ACTIONS(78),
    [anon_sym_false] = ACTIONS(78),
    [sym_string] = ACTIONS(76),
    [sym_raw_verbatim] = ACTIONS(76),
    [sym_raw_string] = ACTIONS(76),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(76),
    [sym_splat] = ACTIONS(76),
    [sym_sigil] = ACTIONS(76),
    [sym_splice] = ACTIONS(78),
    [sym_bang_sigil] = ACTIONS(76),
    [sym_adapter] = ACTIONS(76),
    [sym_number] = ACTIONS(76),
    [sym_constructor] = ACTIONS(76),
    [anon_sym_PIPE_GT] = ACTIONS(76),
    [anon_sym_GT_GT] = ACTIONS(76),
    [anon_sym_DASH_GT] = ACTIONS(76),
    [anon_sym_COLON_COLON] = ACTIONS(76),
    [anon_sym_EQ_EQ] = ACTIONS(76),
    [anon_sym_BANG_EQ] = ACTIONS(76),
    [anon_sym_LT_EQ] = ACTIONS(76),
    [anon_sym_GT_EQ] = ACTIONS(76),
    [anon_sym_AMP_AMP] = ACTIONS(76),
    [anon_sym_PIPE_PIPE] = ACTIONS(76),
    [anon_sym_DOT_DOT] = ACTIONS(76),
    [anon_sym_PIPE] = ACTIONS(78),
    [anon_sym_EQ] = ACTIONS(78),
    [anon_sym_LT] = ACTIONS(78),
    [anon_sym_GT] = ACTIONS(78),
    [anon_sym_PLUS] = ACTIONS(76),
    [anon_sym_DASH] = ACTIONS(78),
    [anon_sym_STAR] = ACTIONS(76),
    [anon_sym_SLASH] = ACTIONS(78),
    [anon_sym_PERCENT] = ACTIONS(76),
    [anon_sym_CARET] = ACTIONS(76),
    [anon_sym_DOT] = ACTIONS(78),
    [anon_sym_LPAREN] = ACTIONS(76),
    [anon_sym_RPAREN] = ACTIONS(76),
    [anon_sym_LBRACK] = ACTIONS(78),
    [anon_sym_RBRACK] = ACTIONS(76),
    [anon_sym_LBRACE] = ACTIONS(76),
    [anon_sym_RBRACE] = ACTIONS(76),
    [anon_sym_SEMI] = ACTIONS(76),
    [anon_sym_COMMA] = ACTIONS(76),
    [anon_sym_COLON] = ACTIONS(78),
    [sym_stray] = ACTIONS(78),
    [sym_type_param] = ACTIONS(76),
    [sym_yaml_marker] = ACTIONS(76),
    [sym_yaml_key] = ACTIONS(76),
    [sym_yaml_text] = ACTIONS(76),
    [sym_yaml_for] = ACTIONS(76),
    [sym_yaml_hole] = ACTIONS(76),
    [sym__yaml_end] = ACTIONS(76),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(70),
    [sym_identifier] = ACTIONS(74),
    [sym_comment] = ACTIONS(3),
    [sym_hash_line] = ACTIONS(70),
    [sym_attribute] = ACTIONS(70),
    [anon_sym_let] = ACTIONS(74),
    [anon_sym__] = ACTIONS(74),
    [anon_sym_type] = ACTIONS(74),
    [anon_sym_in] = ACTIONS(74),
    [anon_sym_fun] = ACTIONS(74),
    [anon_sym_match] = ACTIONS(74),
    [anon_sym_with] = ACTIONS(74),
    [anon_sym_of] = ACTIONS(74),
    [anon_sym_if] = ACTIONS(74),
    [anon_sym_then] = ACTIONS(74),
    [anon_sym_elif] = ACTIONS(74),
    [anon_sym_else] = ACTIONS(74),
    [anon_sym_when] = ACTIONS(74),
    [anon_sym_from] = ACTIONS(74),
    [anon_sym_to] = ACTIONS(74),
    [anon_sym_for] = ACTIONS(74),
    [anon_sym_do] = ACTIONS(74),
    [anon_sym_module] = ACTIONS(74),
    [anon_sym_import] = ACTIONS(74),
    [anon_sym_within] = ACTIONS(74),
    [anon_sym_true] = ACTIONS(74),
    [anon_sym_false] = ACTIONS(74),
    [sym_string] = ACTIONS(70),
    [sym_raw_verbatim] = ACTIONS(70),
    [sym_raw_string] = ACTIONS(70),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(70),
    [sym_splat] = ACTIONS(70),
    [sym_sigil] = ACTIONS(70),
    [sym_splice] = ACTIONS(74),
    [sym_bang_sigil] = ACTIONS(70),
    [sym_adapter] = ACTIONS(70),
    [sym_number] = ACTIONS(70),
    [sym_constructor] = ACTIONS(80),
    [anon_sym_PIPE_GT] = ACTIONS(70),
    [anon_sym_GT_GT] = ACTIONS(70),
    [anon_sym_DASH_GT] = ACTIONS(70),
    [anon_sym_COLON_COLON] = ACTIONS(70),
    [anon_sym_EQ_EQ] = ACTIONS(70),
    [anon_sym_BANG_EQ] = ACTIONS(70),
    [anon_sym_LT_EQ] = ACTIONS(70),
    [anon_sym_GT_EQ] = ACTIONS(70),
    [anon_sym_AMP_AMP] = ACTIONS(70),
    [anon_sym_PIPE_PIPE] = ACTIONS(70),
    [anon_sym_DOT_DOT] = ACTIONS(70),
    [anon_sym_PIPE] = ACTIONS(74),
    [anon_sym_EQ] = ACTIONS(74),
    [anon_sym_LT] = ACTIONS(74),
    [anon_sym_GT] = ACTIONS(74),
    [anon_sym_PLUS] = ACTIONS(70),
    [anon_sym_DASH] = ACTIONS(74),
    [anon_sym_STAR] = ACTIONS(70),
    [anon_sym_SLASH] = ACTIONS(74),
    [anon_sym_PERCENT] = ACTIONS(70),
    [anon_sym_CARET] = ACTIONS(70),
    [anon_sym_DOT] = ACTIONS(74),
    [anon_sym_LPAREN] = ACTIONS(70),
    [anon_sym_RPAREN] = ACTIONS(70),
    [anon_sym_LBRACK] = ACTIONS(74),
    [anon_sym_RBRACK] = ACTIONS(70),
    [anon_sym_LBRACE] = ACTIONS(70),
    [anon_sym_RBRACE] = ACTIONS(70),
    [anon_sym_SEMI] = ACTIONS(70),
    [anon_sym_COMMA] = ACTIONS(70),
    [anon_sym_COLON] = ACTIONS(74),
    [sym_stray] = ACTIONS(74),
    [sym_type_param] = ACTIONS(70),
    [sym_yaml_marker] = ACTIONS(70),
    [sym_yaml_key] = ACTIONS(70),
    [sym_yaml_text] = ACTIONS(70),
    [sym_yaml_for] = ACTIONS(70),
    [sym_yaml_hole] = ACTIONS(70),
    [sym__yaml_end] = ACTIONS(70),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(70),
    [sym_identifier] = ACTIONS(74),
    [sym_comment] = ACTIONS(3),
    [sym_hash_line] = ACTIONS(70),
    [sym_attribute] = ACTIONS(70),
    [anon_sym_let] = ACTIONS(74),
    [anon_sym__] = ACTIONS(74),
    [anon_sym_type] = ACTIONS(74),
    [anon_sym_in] = ACTIONS(74),
    [anon_sym_fun] = ACTIONS(74),
    [anon_sym_match] = ACTIONS(74),
    [anon_sym_with] = ACTIONS(74),
    [anon_sym_of] = ACTIONS(74),
    [anon_sym_if] = ACTIONS(74),
    [anon_sym_then] = ACTIONS(74),
    [anon_sym_elif] = ACTIONS(74),
    [anon_sym_else] = ACTIONS(74),
    [anon_sym_when] = ACTIONS(74),
    [anon_sym_from] = ACTIONS(74),
    [anon_sym_to] = ACTIONS(74),
    [anon_sym_for] = ACTIONS(74),
    [anon_sym_do] = ACTIONS(74),
    [anon_sym_module] = ACTIONS(74),
    [anon_sym_import] = ACTIONS(74),
    [anon_sym_within] = ACTIONS(74),
    [anon_sym_true] = ACTIONS(74),
    [anon_sym_false] = ACTIONS(74),
    [sym_string] = ACTIONS(70),
    [sym_raw_verbatim] = ACTIONS(70),
    [sym_raw_string] = ACTIONS(70),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(70),
    [sym_splat] = ACTIONS(70),
    [sym_sigil] = ACTIONS(70),
    [sym_splice] = ACTIONS(74),
    [sym_bang_sigil] = ACTIONS(70),
    [sym_adapter] = ACTIONS(70),
    [sym_number] = ACTIONS(70),
    [sym_constructor] = ACTIONS(70),
    [anon_sym_PIPE_GT] = ACTIONS(70),
    [anon_sym_GT_GT] = ACTIONS(70),
    [anon_sym_DASH_GT] = ACTIONS(70),
    [anon_sym_COLON_COLON] = ACTIONS(70),
    [anon_sym_EQ_EQ] = ACTIONS(70),
    [anon_sym_BANG_EQ] = ACTIONS(70),
    [anon_sym_LT_EQ] = ACTIONS(70),
    [anon_sym_GT_EQ] = ACTIONS(70),
    [anon_sym_AMP_AMP] = ACTIONS(70),
    [anon_sym_PIPE_PIPE] = ACTIONS(70),
    [anon_sym_DOT_DOT] = ACTIONS(70),
    [anon_sym_PIPE] = ACTIONS(74),
    [anon_sym_EQ] = ACTIONS(74),
    [anon_sym_LT] = ACTIONS(74),
    [anon_sym_GT] = ACTIONS(74),
    [anon_sym_PLUS] = ACTIONS(70),
    [anon_sym_DASH] = ACTIONS(74),
    [anon_sym_STAR] = ACTIONS(70),
    [anon_sym_SLASH] = ACTIONS(74),
    [anon_sym_PERCENT] = ACTIONS(70),
    [anon_sym_CARET] = ACTIONS(70),
    [anon_sym_DOT] = ACTIONS(74),
    [anon_sym_LPAREN] = ACTIONS(70),
    [anon_sym_RPAREN] = ACTIONS(70),
    [anon_sym_LBRACK] = ACTIONS(74),
    [anon_sym_RBRACK] = ACTIONS(70),
    [anon_sym_LBRACE] = ACTIONS(70),
    [anon_sym_RBRACE] = ACTIONS(70),
    [anon_sym_SEMI] = ACTIONS(70),
    [anon_sym_COMMA] = ACTIONS(70),
    [anon_sym_COLON] = ACTIONS(74),
    [sym_stray] = ACTIONS(74),
    [sym_type_param] = ACTIONS(70),
    [sym_yaml_marker] = ACTIONS(70),
    [sym_yaml_key] = ACTIONS(70),
    [sym_yaml_text] = ACTIONS(70),
    [sym_yaml_for] = ACTIONS(70),
    [sym_yaml_hole] = ACTIONS(70),
    [sym__yaml_end] = ACTIONS(70),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(82),
    [sym_identifier] = ACTIONS(84),
    [sym_comment] = ACTIONS(3),
    [sym_hash_line] = ACTIONS(82),
    [sym_attribute] = ACTIONS(82),
    [anon_sym_let] = ACTIONS(84),
    [anon_sym__] = ACTIONS(84),
    [anon_sym_type] = ACTIONS(84),
    [anon_sym_in] = ACTIONS(84),
    [anon_sym_fun] = ACTIONS(84),
    [anon_sym_match] = ACTIONS(84),
    [anon_sym_with] = ACTIONS(84),
    [anon_sym_of] = ACTIONS(84),
    [anon_sym_if] = ACTIONS(84),
    [anon_sym_then] = ACTIONS(84),
    [anon_sym_elif] = ACTIONS(84),
    [anon_sym_else] = ACTIONS(84),
    [anon_sym_when] = ACTIONS(84),
    [anon_sym_from] = ACTIONS(84),
    [anon_sym_to] = ACTIONS(84),
    [anon_sym_for] = ACTIONS(84),
    [anon_sym_do] = ACTIONS(84),
    [anon_sym_module] = ACTIONS(84),
    [anon_sym_import] = ACTIONS(84),
    [anon_sym_within] = ACTIONS(84),
    [anon_sym_true] = ACTIONS(84),
    [anon_sym_false] = ACTIONS(84),
    [sym_string] = ACTIONS(82),
    [sym_raw_verbatim] = ACTIONS(82),
    [sym_raw_string] = ACTIONS(82),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(82),
    [sym_splat] = ACTIONS(82),
    [sym_sigil] = ACTIONS(82),
    [sym_splice] = ACTIONS(84),
    [sym_bang_sigil] = ACTIONS(82),
    [sym_adapter] = ACTIONS(82),
    [sym_number] = ACTIONS(82),
    [sym_constructor] = ACTIONS(82),
    [anon_sym_PIPE_GT] = ACTIONS(82),
    [anon_sym_GT_GT] = ACTIONS(82),
    [anon_sym_DASH_GT] = ACTIONS(82),
    [anon_sym_COLON_COLON] = ACTIONS(82),
    [anon_sym_EQ_EQ] = ACTIONS(82),
    [anon_sym_BANG_EQ] = ACTIONS(82),
    [anon_sym_LT_EQ] = ACTIONS(82),
    [anon_sym_GT_EQ] = ACTIONS(82),
    [anon_sym_AMP_AMP] = ACTIONS(82),
    [anon_sym_PIPE_PIPE] = ACTIONS(82),
    [anon_sym_DOT_DOT] = ACTIONS(82),
    [anon_sym_PIPE] = ACTIONS(84),
    [anon_sym_EQ] = ACTIONS(84),
    [anon_sym_LT] = ACTIONS(84),
    [anon_sym_GT] = ACTIONS(84),
    [anon_sym_PLUS] = ACTIONS(82),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym_STAR] = ACTIONS(82),
    [anon_sym_SLASH] = ACTIONS(84),
    [anon_sym_PERCENT] = ACTIONS(82),
    [anon_sym_CARET] = ACTIONS(82),
    [anon_sym_DOT] = ACTIONS(84),
    [anon_sym_LPAREN] = ACTIONS(82),
    [anon_sym_RPAREN] = ACTIONS(82),
    [anon_sym_LBRACK] = ACTIONS(84),
    [anon_sym_RBRACK] = ACTIONS(82),
    [anon_sym_LBRACE] = ACTIONS(82),
    [anon_sym_RBRACE] = ACTIONS(82),
    [anon_sym_SEMI] = ACTIONS(82),
    [anon_sym_COMMA] = ACTIONS(82),
    [anon_sym_COLON] = ACTIONS(84),
    [sym_stray] = ACTIONS(84),
    [sym_type_param] = ACTIONS(82),
    [sym_yaml_marker] = ACTIONS(82),
    [sym_yaml_key] = ACTIONS(82),
    [sym_yaml_text] = ACTIONS(82),
    [sym_yaml_for] = ACTIONS(82),
    [sym_yaml_hole] = ACTIONS(82),
    [sym__yaml_end] = ACTIONS(82),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(86),
    [sym_identifier] = ACTIONS(88),
    [sym_comment] = ACTIONS(3),
    [sym_hash_line] = ACTIONS(86),
    [sym_attribute] = ACTIONS(86),
    [anon_sym_let] = ACTIONS(88),
    [anon_sym__] = ACTIONS(88),
    [anon_sym_type] = ACTIONS(88),
    [anon_sym_in] = ACTIONS(88),
    [anon_sym_fun] = ACTIONS(88),
    [anon_sym_match] = ACTIONS(88),
    [anon_sym_with] = ACTIONS(88),
    [anon_sym_of] = ACTIONS(88),
    [anon_sym_if] = ACTIONS(88),
    [anon_sym_then] = ACTIONS(88),
    [anon_sym_elif] = ACTIONS(88),
    [anon_sym_else] = ACTIONS(88),
    [anon_sym_when] = ACTIONS(88),
    [anon_sym_from] = ACTIONS(88),
    [anon_sym_to] = ACTIONS(88),
    [anon_sym_for] = ACTIONS(88),
    [anon_sym_do] = ACTIONS(88),
    [anon_sym_module] = ACTIONS(88),
    [anon_sym_import] = ACTIONS(88),
    [anon_sym_within] = ACTIONS(88),
    [anon_sym_true] = ACTIONS(88),
    [anon_sym_false] = ACTIONS(88),
    [sym_string] = ACTIONS(86),
    [sym_raw_verbatim] = ACTIONS(86),
    [sym_raw_string] = ACTIONS(86),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(86),
    [sym_splat] = ACTIONS(86),
    [sym_sigil] = ACTIONS(86),
    [sym_splice] = ACTIONS(88),
    [sym_bang_sigil] = ACTIONS(86),
    [sym_adapter] = ACTIONS(86),
    [sym_number] = ACTIONS(86),
    [sym_constructor] = ACTIONS(86),
    [anon_sym_PIPE_GT] = ACTIONS(86),
    [anon_sym_GT_GT] = ACTIONS(86),
    [anon_sym_DASH_GT] = ACTIONS(86),
    [anon_sym_COLON_COLON] = ACTIONS(86),
    [anon_sym_EQ_EQ] = ACTIONS(86),
    [anon_sym_BANG_EQ] = ACTIONS(86),
    [anon_sym_LT_EQ] = ACTIONS(86),
    [anon_sym_GT_EQ] = ACTIONS(86),
    [anon_sym_AMP_AMP] = ACTIONS(86),
    [anon_sym_PIPE_PIPE] = ACTIONS(86),
    [anon_sym_DOT_DOT] = ACTIONS(86),
    [anon_sym_PIPE] = ACTIONS(88),
    [anon_sym_EQ] = ACTIONS(88),
    [anon_sym_LT] = ACTIONS(88),
    [anon_sym_GT] = ACTIONS(88),
    [anon_sym_PLUS] = ACTIONS(86),
    [anon_sym_DASH] = ACTIONS(88),
    [anon_sym_STAR] = ACTIONS(86),
    [anon_sym_SLASH] = ACTIONS(88),
    [anon_sym_PERCENT] = ACTIONS(86),
    [anon_sym_CARET] = ACTIONS(86),
    [anon_sym_DOT] = ACTIONS(88),
    [anon_sym_LPAREN] = ACTIONS(86),
    [anon_sym_RPAREN] = ACTIONS(86),
    [anon_sym_LBRACK] = ACTIONS(88),
    [anon_sym_RBRACK] = ACTIONS(86),
    [anon_sym_LBRACE] = ACTIONS(86),
    [anon_sym_RBRACE] = ACTIONS(86),
    [anon_sym_SEMI] = ACTIONS(86),
    [anon_sym_COMMA] = ACTIONS(86),
    [anon_sym_COLON] = ACTIONS(88),
    [sym_stray] = ACTIONS(88),
    [sym_type_param] = ACTIONS(86),
    [sym_yaml_marker] = ACTIONS(86),
    [sym_yaml_key] = ACTIONS(86),
    [sym_yaml_text] = ACTIONS(86),
    [sym_yaml_for] = ACTIONS(86),
    [sym_yaml_hole] = ACTIONS(86),
    [sym__yaml_end] = ACTIONS(86),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(90),
    [sym_identifier] = ACTIONS(92),
    [sym_comment] = ACTIONS(3),
    [sym_hash_line] = ACTIONS(90),
    [sym_attribute] = ACTIONS(90),
    [anon_sym_let] = ACTIONS(92),
    [anon_sym__] = ACTIONS(92),
    [anon_sym_type] = ACTIONS(92),
    [anon_sym_in] = ACTIONS(92),
    [anon_sym_fun] = ACTIONS(92),
    [anon_sym_match] = ACTIONS(92),
    [anon_sym_with] = ACTIONS(92),
    [anon_sym_of] = ACTIONS(92),
    [anon_sym_if] = ACTIONS(92),
    [anon_sym_then] = ACTIONS(92),
    [anon_sym_elif] = ACTIONS(92),
    [anon_sym_else] = ACTIONS(92),
    [anon_sym_when] = ACTIONS(92),
    [anon_sym_from] = ACTIONS(92),
    [anon_sym_to] = ACTIONS(92),
    [anon_sym_for] = ACTIONS(92),
    [anon_sym_do] = ACTIONS(92),
    [anon_sym_module] = ACTIONS(92),
    [anon_sym_import] = ACTIONS(92),
    [anon_sym_within] = ACTIONS(92),
    [anon_sym_true] = ACTIONS(92),
    [anon_sym_false] = ACTIONS(92),
    [sym_string] = ACTIONS(90),
    [sym_raw_verbatim] = ACTIONS(90),
    [sym_raw_string] = ACTIONS(90),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(90),
    [sym_splat] = ACTIONS(90),
    [sym_sigil] = ACTIONS(90),
    [sym_splice] = ACTIONS(92),
    [sym_bang_sigil] = ACTIONS(90),
    [sym_adapter] = ACTIONS(90),
    [sym_number] = ACTIONS(90),
    [sym_constructor] = ACTIONS(90),
    [anon_sym_PIPE_GT] = ACTIONS(90),
    [anon_sym_GT_GT] = ACTIONS(90),
    [anon_sym_DASH_GT] = ACTIONS(90),
    [anon_sym_COLON_COLON] = ACTIONS(90),
    [anon_sym_EQ_EQ] = ACTIONS(90),
    [anon_sym_BANG_EQ] = ACTIONS(90),
    [anon_sym_LT_EQ] = ACTIONS(90),
    [anon_sym_GT_EQ] = ACTIONS(90),
    [anon_sym_AMP_AMP] = ACTIONS(90),
    [anon_sym_PIPE_PIPE] = ACTIONS(90),
    [anon_sym_DOT_DOT] = ACTIONS(90),
    [anon_sym_PIPE] = ACTIONS(92),
    [anon_sym_EQ] = ACTIONS(92),
    [anon_sym_LT] = ACTIONS(92),
    [anon_sym_GT] = ACTIONS(92),
    [anon_sym_PLUS] = ACTIONS(90),
    [anon_sym_DASH] = ACTIONS(92),
    [anon_sym_STAR] = ACTIONS(90),
    [anon_sym_SLASH] = ACTIONS(92),
    [anon_sym_PERCENT] = ACTIONS(90),
    [anon_sym_CARET] = ACTIONS(90),
    [anon_sym_DOT] = ACTIONS(92),
    [anon_sym_LPAREN] = ACTIONS(90),
    [anon_sym_RPAREN] = ACTIONS(90),
    [anon_sym_LBRACK] = ACTIONS(92),
    [anon_sym_RBRACK] = ACTIONS(90),
    [anon_sym_LBRACE] = ACTIONS(90),
    [anon_sym_RBRACE] = ACTIONS(90),
    [anon_sym_SEMI] = ACTIONS(90),
    [anon_sym_COMMA] = ACTIONS(90),
    [anon_sym_COLON] = ACTIONS(92),
    [sym_stray] = ACTIONS(92),
    [sym_type_param] = ACTIONS(90),
    [sym_yaml_marker] = ACTIONS(90),
    [sym_yaml_key] = ACTIONS(90),
    [sym_yaml_text] = ACTIONS(90),
    [sym_yaml_for] = ACTIONS(90),
    [sym_yaml_hole] = ACTIONS(90),
    [sym__yaml_end] = ACTIONS(90),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(94),
    [sym_identifier] = ACTIONS(96),
    [sym_comment] = ACTIONS(3),
    [sym_hash_line] = ACTIONS(94),
    [sym_attribute] = ACTIONS(94),
    [anon_sym_let] = ACTIONS(96),
    [anon_sym__] = ACTIONS(96),
    [anon_sym_type] = ACTIONS(96),
    [anon_sym_in] = ACTIONS(96),
    [anon_sym_fun] = ACTIONS(96),
    [anon_sym_match] = ACTIONS(96),
    [anon_sym_with] = ACTIONS(96),
    [anon_sym_of] = ACTIONS(96),
    [anon_sym_if] = ACTIONS(96),
    [anon_sym_then] = ACTIONS(96),
    [anon_sym_elif] = ACTIONS(96),
    [anon_sym_else] = ACTIONS(96),
    [anon_sym_when] = ACTIONS(96),
    [anon_sym_from] = ACTIONS(96),
    [anon_sym_to] = ACTIONS(96),
    [anon_sym_for] = ACTIONS(96),
    [anon_sym_do] = ACTIONS(96),
    [anon_sym_module] = ACTIONS(96),
    [anon_sym_import] = ACTIONS(96),
    [anon_sym_within] = ACTIONS(96),
    [anon_sym_true] = ACTIONS(96),
    [anon_sym_false] = ACTIONS(96),
    [sym_string] = ACTIONS(94),
    [sym_raw_verbatim] = ACTIONS(94),
    [sym_raw_string] = ACTIONS(94),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(94),
    [sym_splat] = ACTIONS(94),
    [sym_sigil] = ACTIONS(94),
    [sym_splice] = ACTIONS(96),
    [sym_bang_sigil] = ACTIONS(94),
    [sym_adapter] = ACTIONS(94),
    [sym_number] = ACTIONS(94),
    [sym_constructor] = ACTIONS(94),
    [anon_sym_PIPE_GT] = ACTIONS(94),
    [anon_sym_GT_GT] = ACTIONS(94),
    [anon_sym_DASH_GT] = ACTIONS(94),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ] = ACTIONS(94),
    [anon_sym_BANG_EQ] = ACTIONS(94),
    [anon_sym_LT_EQ] = ACTIONS(94),
    [anon_sym_GT_EQ] = ACTIONS(94),
    [anon_sym_AMP_AMP] = ACTIONS(94),
    [anon_sym_PIPE_PIPE] = ACTIONS(94),
    [anon_sym_DOT_DOT] = ACTIONS(94),
    [anon_sym_PIPE] = ACTIONS(96),
    [anon_sym_EQ] = ACTIONS(96),
    [anon_sym_LT] = ACTIONS(96),
    [anon_sym_GT] = ACTIONS(96),
    [anon_sym_PLUS] = ACTIONS(94),
    [anon_sym_DASH] = ACTIONS(96),
    [anon_sym_STAR] = ACTIONS(94),
    [anon_sym_SLASH] = ACTIONS(96),
    [anon_sym_PERCENT] = ACTIONS(94),
    [anon_sym_CARET] = ACTIONS(94),
    [anon_sym_DOT] = ACTIONS(96),
    [anon_sym_LPAREN] = ACTIONS(94),
    [anon_sym_RPAREN] = ACTIONS(94),
    [anon_sym_LBRACK] = ACTIONS(96),
    [anon_sym_RBRACK] = ACTIONS(94),
    [anon_sym_LBRACE] = ACTIONS(94),
    [anon_sym_RBRACE] = ACTIONS(94),
    [anon_sym_SEMI] = ACTIONS(94),
    [anon_sym_COMMA] = ACTIONS(94),
    [anon_sym_COLON] = ACTIONS(96),
    [sym_stray] = ACTIONS(96),
    [sym_type_param] = ACTIONS(94),
    [sym_yaml_marker] = ACTIONS(94),
    [sym_yaml_key] = ACTIONS(94),
    [sym_yaml_text] = ACTIONS(94),
    [sym_yaml_for] = ACTIONS(94),
    [sym_yaml_hole] = ACTIONS(94),
    [sym__yaml_end] = ACTIONS(94),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(98),
    [sym_identifier] = ACTIONS(100),
    [sym_comment] = ACTIONS(3),
    [sym_hash_line] = ACTIONS(98),
    [sym_attribute] = ACTIONS(98),
    [anon_sym_let] = ACTIONS(100),
    [anon_sym__] = ACTIONS(100),
    [anon_sym_type] = ACTIONS(100),
    [anon_sym_in] = ACTIONS(100),
    [anon_sym_fun] = ACTIONS(100),
    [anon_sym_match] = ACTIONS(100),
    [anon_sym_with] = ACTIONS(100),
    [anon_sym_of] = ACTIONS(100),
    [anon_sym_if] = ACTIONS(100),
    [anon_sym_then] = ACTIONS(100),
    [anon_sym_elif] = ACTIONS(100),
    [anon_sym_else] = ACTIONS(100),
    [anon_sym_when] = ACTIONS(100),
    [anon_sym_from] = ACTIONS(100),
    [anon_sym_to] = ACTIONS(100),
    [anon_sym_for] = ACTIONS(100),
    [anon_sym_do] = ACTIONS(100),
    [anon_sym_module] = ACTIONS(100),
    [anon_sym_import] = ACTIONS(100),
    [anon_sym_within] = ACTIONS(100),
    [anon_sym_true] = ACTIONS(100),
    [anon_sym_false] = ACTIONS(100),
    [sym_string] = ACTIONS(98),
    [sym_raw_verbatim] = ACTIONS(98),
    [sym_raw_string] = ACTIONS(98),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(98),
    [sym_splat] = ACTIONS(98),
    [sym_sigil] = ACTIONS(98),
    [sym_splice] = ACTIONS(100),
    [sym_bang_sigil] = ACTIONS(98),
    [sym_adapter] = ACTIONS(98),
    [sym_number] = ACTIONS(98),
    [sym_constructor] = ACTIONS(98),
    [anon_sym_PIPE_GT] = ACTIONS(98),
    [anon_sym_GT_GT] = ACTIONS(98),
    [anon_sym_DASH_GT] = ACTIONS(98),
    [anon_sym_COLON_COLON] = ACTIONS(98),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_BANG_EQ] = ACTIONS(98),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(98),
    [anon_sym_AMP_AMP] = ACTIONS(98),
    [anon_sym_PIPE_PIPE] = ACTIONS(98),
    [anon_sym_DOT_DOT] = ACTIONS(98),
    [anon_sym_PIPE] = ACTIONS(100),
    [anon_sym_EQ] = ACTIONS(100),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(100),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(100),
    [anon_sym_STAR] = ACTIONS(98),
    [anon_sym_SLASH] = ACTIONS(100),
    [anon_sym_PERCENT] = ACTIONS(98),
    [anon_sym_CARET] = ACTIONS(98),
    [anon_sym_DOT] = ACTIONS(100),
    [anon_sym_LPAREN] = ACTIONS(98),
    [anon_sym_RPAREN] = ACTIONS(98),
    [anon_sym_LBRACK] = ACTIONS(100),
    [anon_sym_RBRACK] = ACTIONS(98),
    [anon_sym_LBRACE] = ACTIONS(98),
    [anon_sym_RBRACE] = ACTIONS(98),
    [anon_sym_SEMI] = ACTIONS(98),
    [anon_sym_COMMA] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(100),
    [sym_stray] = ACTIONS(100),
    [sym_type_param] = ACTIONS(98),
    [sym_yaml_marker] = ACTIONS(98),
    [sym_yaml_key] = ACTIONS(98),
    [sym_yaml_text] = ACTIONS(98),
    [sym_yaml_for] = ACTIONS(98),
    [sym_yaml_hole] = ACTIONS(98),
    [sym__yaml_end] = ACTIONS(98),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(102),
    [sym_identifier] = ACTIONS(104),
    [sym_comment] = ACTIONS(3),
    [sym_hash_line] = ACTIONS(102),
    [sym_attribute] = ACTIONS(102),
    [anon_sym_let] = ACTIONS(104),
    [anon_sym__] = ACTIONS(104),
    [anon_sym_type] = ACTIONS(104),
    [anon_sym_in] = ACTIONS(104),
    [anon_sym_fun] = ACTIONS(104),
    [anon_sym_match] = ACTIONS(104),
    [anon_sym_with] = ACTIONS(104),
    [anon_sym_of] = ACTIONS(104),
    [anon_sym_if] = ACTIONS(104),
    [anon_sym_then] = ACTIONS(104),
    [anon_sym_elif] = ACTIONS(104),
    [anon_sym_else] = ACTIONS(104),
    [anon_sym_when] = ACTIONS(104),
    [anon_sym_from] = ACTIONS(104),
    [anon_sym_to] = ACTIONS(104),
    [anon_sym_for] = ACTIONS(104),
    [anon_sym_do] = ACTIONS(104),
    [anon_sym_module] = ACTIONS(104),
    [anon_sym_import] = ACTIONS(104),
    [anon_sym_within] = ACTIONS(104),
    [anon_sym_true] = ACTIONS(104),
    [anon_sym_false] = ACTIONS(104),
    [sym_string] = ACTIONS(102),
    [sym_raw_verbatim] = ACTIONS(102),
    [sym_raw_string] = ACTIONS(102),
    [anon_sym_DOLLAR_DQUOTE] = ACTIONS(102),
    [sym_splat] = ACTIONS(102),
    [sym_sigil] = ACTIONS(102),
    [sym_splice] = ACTIONS(104),
    [sym_bang_sigil] = ACTIONS(102),
    [sym_adapter] = ACTIONS(102),
    [sym_number] = ACTIONS(102),
    [sym_constructor] = ACTIONS(102),
    [anon_sym_PIPE_GT] = ACTIONS(102),
    [anon_sym_GT_GT] = ACTIONS(102),
    [anon_sym_DASH_GT] = ACTIONS(102),
    [anon_sym_COLON_COLON] = ACTIONS(102),
    [anon_sym_EQ_EQ] = ACTIONS(102),
    [anon_sym_BANG_EQ] = ACTIONS(102),
    [anon_sym_LT_EQ] = ACTIONS(102),
    [anon_sym_GT_EQ] = ACTIONS(102),
    [anon_sym_AMP_AMP] = ACTIONS(102),
    [anon_sym_PIPE_PIPE] = ACTIONS(102),
    [anon_sym_DOT_DOT] = ACTIONS(102),
    [anon_sym_PIPE] = ACTIONS(104),
    [anon_sym_EQ] = ACTIONS(104),
    [anon_sym_LT] = ACTIONS(104),
    [anon_sym_GT] = ACTIONS(104),
    [anon_sym_PLUS] = ACTIONS(102),
    [anon_sym_DASH] = ACTIONS(104),
    [anon_sym_STAR] = ACTIONS(102),
    [anon_sym_SLASH] = ACTIONS(104),
    [anon_sym_PERCENT] = ACTIONS(102),
    [anon_sym_CARET] = ACTIONS(102),
    [anon_sym_DOT] = ACTIONS(104),
    [anon_sym_LPAREN] = ACTIONS(102),
    [anon_sym_RPAREN] = ACTIONS(102),
    [anon_sym_LBRACK] = ACTIONS(104),
    [anon_sym_RBRACK] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(102),
    [anon_sym_RBRACE] = ACTIONS(102),
    [anon_sym_SEMI] = ACTIONS(102),
    [anon_sym_COMMA] = ACTIONS(102),
    [anon_sym_COLON] = ACTIONS(104),
    [sym_stray] = ACTIONS(104),
    [sym_type_param] = ACTIONS(102),
    [sym_yaml_marker] = ACTIONS(102),
    [sym_yaml_key] = ACTIONS(102),
    [sym_yaml_text] = ACTIONS(102),
    [sym_yaml_for] = ACTIONS(102),
    [sym_yaml_hole] = ACTIONS(102),
    [sym__yaml_end] = ACTIONS(102),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(106), 1,
      sym_comment,
    ACTIONS(108), 1,
      anon_sym_DQUOTE,
    ACTIONS(112), 1,
      sym_interp_escape,
    STATE(15), 1,
      aux_sym_interp_string_repeat1,
    ACTIONS(110), 2,
      sym_interp_text,
      sym_interp_hole,
  [17] = 5,
    ACTIONS(106), 1,
      sym_comment,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      sym_interp_escape,
    STATE(16), 1,
      aux_sym_interp_string_repeat1,
    ACTIONS(116), 2,
      sym_interp_text,
      sym_interp_hole,
  [34] = 5,
    ACTIONS(106), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_DQUOTE,
    ACTIONS(125), 1,
      sym_interp_escape,
    STATE(16), 1,
      aux_sym_interp_string_repeat1,
    ACTIONS(122), 2,
      sym_interp_text,
      sym_interp_hole,
  [51] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 17,
  [SMALL_STATE(16)] = 34,
  [SMALL_STATE(17)] = 51,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_punctuation, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_punctuation, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_head, 2, 0, 1),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_head, 2, 0, 1),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_head, 2, 0, 1),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_type_head, 2, 0, 1),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interp_string, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interp_string, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interp_string, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interp_string, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_interp_string_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_interp_string_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interp_string_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [128] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_type_param = 0,
  ts_external_token_yaml_marker = 1,
  ts_external_token_yaml_key = 2,
  ts_external_token_yaml_text = 3,
  ts_external_token_yaml_for = 4,
  ts_external_token_yaml_hole = 5,
  ts_external_token__yaml_end = 6,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_type_param] = sym_type_param,
  [ts_external_token_yaml_marker] = sym_yaml_marker,
  [ts_external_token_yaml_key] = sym_yaml_key,
  [ts_external_token_yaml_text] = sym_yaml_text,
  [ts_external_token_yaml_for] = sym_yaml_for,
  [ts_external_token_yaml_hole] = sym_yaml_hole,
  [ts_external_token__yaml_end] = sym__yaml_end,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_type_param] = true,
    [ts_external_token_yaml_marker] = true,
    [ts_external_token_yaml_key] = true,
    [ts_external_token_yaml_text] = true,
    [ts_external_token_yaml_for] = true,
    [ts_external_token_yaml_hole] = true,
    [ts_external_token__yaml_end] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_weir_external_scanner_create(void);
void tree_sitter_weir_external_scanner_destroy(void *);
bool tree_sitter_weir_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_weir_external_scanner_serialize(void *, char *);
void tree_sitter_weir_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_weir(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_weir_external_scanner_create,
      tree_sitter_weir_external_scanner_destroy,
      tree_sitter_weir_external_scanner_scan,
      tree_sitter_weir_external_scanner_serialize,
      tree_sitter_weir_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
